### PR TITLE
Dictionary-passing Style

### PR DESCRIPTION
**Pull request by kim**
As it turns out, the use of typeclasses (whether in conventional `mtl-style` or the monad morphism approach used previously) leads to various complications due to the additional `ctx` parameter. Since we ultimately evaluate to `MonadIO` (and I don't see any obvious way around that), it also doesn't seem to provide any additional benefit over just passing the `Span` construction and reporting actions as a record "dictionary". On the contrary, this makes things a lot simpler, leverages parametric polymorphism to fix (or modify) the concrete `ctx`, and even allows to change implementations at runtime (which may or may not be useful).

### CODE REVIEW

**Comment by kim** [comment]
@isovector please let me know your thoughts on this one and #4 (which this one is based on). Both should stabilise the surface API for the time being.

**Comment by isovector** [comment]
This is strictly better than the previous implementation, imo.

One question I have is about the existence of the `ctx` parameter entirely -- does it need to be exposed anymore? At work we've existentialized over the entire thing so that we can change the backend through configuration. The presence of explicit dict passing suggests to me this might be a good time to make such a change if you think it might have some value.

**Comment by kim** [comment]
> we've existentialized over the entire thing

Not sure I understand how... you have to disambiguate `ctx` somewhere, no?

That being said, I'm becoming less and less convinced that it is actually necessary to parametrise over the context -- it seems like it should be possible to shoehorn the same type onto any backend representation. Will have to think about this for some more time.

**Comment by isovector** [comment]
We did something like this:

```haskell
data SomeTracing where
    SomeTracing :: HasInstrumentation ctx => OT.Tracing ctx MonadIO -> SomeTracing

withSomeTracing :: SomeTracing -> (forall ctx. HasInstrumentation ctx => OT.Tracing ctx MonadIO -> r) -> r
withSomeTracing (SomeTracing tracing) f = f tracing
```

and then you can describe the actual tracer context via config:

```haskell
getFakeTracing :: MonadIO m => m SomeTracing
getFakeTracing = liftIO $ do
    putStrLn "FYI - No tracing is enabled. Set opentracing.use_tracing = true in config file"
    env <- OTS.newEnv  $ constSampler False
    pure . SomeTracing $ OT.Tracing (OTS.simpleTracer env)
                                    OTS.simpleReporter

getTracingFromConfig
    :: MonadIO m
    => Text
       -- ^ Name of the service being traced 
    -> C.Config
       -- ^ Pass a config with top-level "zipkin" containing fields "host", "port",
       --   and "service_name"
       --   and top-level "sampling."
       --   Valid sampling examples: "sampling.rate_limited = 10",
       --   "sampling.const = false", "sampling.probabilistic = 0.01"
    -> Maybe OT.Sampler
    -> m SomeTracing
getTracingFromConfig serviceName cfg sampler = liftIO $
  C.lookupDefault False cfg "opentracing.use_tracing" >>= \case
      False -> getFakeTracing
      True  -> do
          zHost <- C.require cfg "opentracing.zipkin.host"
          zPort <- show @Int <$> C.require cfg "opentracing.zipkin.port"
          let endpoint = ZR.Endpoint (Just serviceName) (Just $ read zHost)
                                     Nothing (Just $ read zPort)

          sampler <- maybe (error "Need a valid samplier") id <$> pure mSampler
          env     <- Z.newEnv sampler
          renv    <- ZR.newEnv ZR.V2 endpoint zHost (read zPort) OT.jsonAssoc
          seq sampler . pure $ SomeTracing $ OT.Tracing (Z.zipkinTracer env)
                                                        (ZR.zipkinHttpReporter renv)
```

**Comment by kim** [comment]
Ah ok. This is certainly useful for exactly what you describe. I don't see, however, how it could eliminate the `ctx` parameter entirely from the API. Therefore, I'm a bit hesitant to add this to the library.

Let me see if I can convince myself that a single `Context` type would suffice. Then the propagation stuff could go into the dictionary as well, and all would be nice and simple :)

**Comment by kim** [comment]
Alright, I think this works out nicely.

Note two things:
* I kind of couldn't resist to provide `traceInject`/`traceExtract` (demanded in the spec), which works out nicely but requires `TypeApplications`. Guess this is alright.
* There's nothing to prevent constructing nonsensical `Propagation` pairs. Not sure if there should, and how.

**Comment by kim** [comment]
Oh, and `OpenTracing.Zipkin` is now obviously pretty redundant. Generally, for backends only the reporter part needs to be implemented.

I'll remove it in a subsequent PR, as this got a bit out of hand by now.

**Pull request merged**
