### PR TITLE
Setting thrift to 0.11.0

### PR DESCRIPTION
**Pull request by mjrussell**
I was a bit annoyed by having to using `allow: newer` in all my projects that used jaeger. I took a look at `thrift` and it turns out they've fixed the version bounds on vector in this [pr](https://github.com/apache/thrift/pull/1145). There's been a subsequent release (0.11.0) but it hasn't made its way to hackage for some reason (see https://issues.apache.org/jira/browse/THRIFT-4491). I just tweaked the version bounds and hit a couple of compile errors with the auto generated source. I didn't see what you were running to generate them, otherwise I would have been happy to do so. I've enabled edited from maintainers in case you want to run the thrift generation and push to this branch and I can test it out with jaeger.

Thanks!

### CODE REVIEW

**Comment by kim** [comment]
Thanks for targeting this. You can generate the sources using the thrift compiler **at version 0.11.0** and https://github.com/jaegertracing/jaeger-idl resp. https://github.com/openzipkin/zipkin-api (hopefully the `zipkin[c|C]ore.thrift` are the same in both repositories):

`thrift --gen hs -out opentracing-jaeger/gen-src $JAEGER_IDL_ROOT/thrift/jaeger.thrift`
`thrift --gen hs -out opentracing-zipkin-v1/gen-src $ZIPKIN_API_ROOT/thrift/zipkinCore.thrift`

I am a bit on the fence whether I should support jaeger/thrift down the road -- the situation around the Haskell thrift bindings' maintenance / releases seem to preclude that any of the subpackages here which use thrift will ever make it to Hackage. Given that Zipkin seems to move to HTTP/JSON entirely, and Jaeger being committed to staying compatible, it seems more trouble than it's worth to support anything but the Zipkin V2 API for this library...

**Comment by mjrussell** [comment]
Thanks for the nudge in the right direction on the bindings. 

Interesting about only supporting zipkin, I didn't realize that jaeger was fully compatible with zipkin. I would think that a UDP approach would work better in a production system with high volumes of traffic, but I've also heard that the Haskell thrift implementation is quite slow (compared with the C++ implementation). Its great that the abstractions you've added already would make switching from jaeger to zipkin format quite trivial.

**Comment by mjrussell** [comment]
Looks like thrift did get released on hackage recently (0.11 and 0.12) which is great! We've been using the zipkin API with a Jaeger backend and its worked perfectly. I might still see about updating the bindings now that there's an official thrift release though.

**Comment by kim** [comment]
Compiles with latest IDLs, thrift compiler 0.11, and 0.11.0 lower bound on the Haskell thrift library.

There seems to be a field addition, but also a new thrift protocol, so I'm not sure how compatible this is with the server side.

**Pull request merged**
